# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d5a2ea4c59de6310928657dcd3dd7eafc6d1df5f1372b891dec41de9f56647eb19046e8f2d940531f9f2b3d0dcb22d288555592fb84420d23a07d27828656f

test:
  secret_key_base: 1693f49254df084c0219c51814713db1d4185ef8c3894eca1b6d776a2919b99c7b517bfbeb3d1c3e9b3d1504529e20ebd411510cc447b03f7db894178dc41928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1ba9e26d2a4dd8f22a554c65ddcead02fdf70c923928dedd056b888fdebbae8bdc62d3b5e47b10b7c12d4d329067a37b0fb89fc1adbc843b4073bf1986d65f2d
